### PR TITLE
Update to .NET 8

### PR DESCRIPTION
**Pull request by rido-min**
This PR updates all dotnet projects to use net8, the new LTS released earlier this month.

### CODE REVIEW

**Comment by jrdouceur** [comment]
The codegen folders cannot be changed from a fork, because the DTDLParser-PR flow does not work for forks, and it verifies that the code generation proceeds correctly.  Can you resubmit this from a branch on this repo?

**Comment by rido-min** [comment]
this PR is not from a fork, I avoid to update anything in the `gen` folder, but it still fails because the tutorials cannot be updated.

I'm closing this PR, and sync offline to figure out the best way to proceed.

**Comment by jrdouceur** [comment]
Try renaming the branch to "meta-gen/net8" and pushing again.  This is an annoying quirk of the PR flow; sorry about this.

**Comment by rido-min** [comment]
and then.. can I update files under `dotnet/gen` ? I'm wondering how to update the tutorials

**Comment by jrdouceur** [comment]
bash Develop.sh
This will update everything, including tutorials.
The PR pipeline will also do this for you, and it will add a commit to your PR branch with the generated files.

**Pull request closed without merging**
