### PR TITLE
Update tutorials to illustrate new APIs

### PR DESCRIPTION
**Pull request by jrdouceur**

### CODE REVIEW

**Comment by jrdouceur** [comment]
Previous PR https://github.com/digitaltwinconsortium/DTDLParser/pull/64 could not update generation input files due to lack of meta-gen prefix on branch name.

**Comment by rido-min** [comment]
I'm a bit confused with Tutorial 5, seems that we are showing 3 ways to accomplish the same task:

1. Using DTContentInfo
2. Using Syntethic Properties
3. Using Reflection

Which one should be used when? I'm in favor of 2), as this seems the most appropriate for a former ObjectModel

Nit. Can we use `ToList().ForEach()` instead of traditional `foreach` loops

**Comment by jrdouceur** [comment]
Yes, we're showing 3 approaches.  This tutorial is not advocating a particular approach but rather illustrating how each can be used.  There are advantages and disadvantages to each.

Regarding `ToList().ForEach()`:  Sure, we could do this, but I don't think it is preferable.  Neither does Eric Lippert (principal dev on C# compiler team): https://ericlippert.com/2009/05/18/foreach-vs-foreach/

**Comment by rido-min** [comment]
from the same blog post:

> There are usages for such a thing; in particular I have used that method for “dump this sequence to the debugger display"

I guess this is exactly the scenario for samples and tutorials

**Comment by jrdouceur** [comment]
How about if I restructure the tutorial to have a "preferred approach" first, followed by "alternative approaches".  Still provides the info if someone has a use case for the other approaches, but encourages the one we consider to be cleanest.

**Comment by jrdouceur** [comment]
“dump this sequence to the debugger display" is transient code that is never checked in.  Tutorials, as you argued above, should tutor the preferred approach to be used in production code.

**Comment by rido-min** [comment]
> “dump this sequence to the debugger display" is transient code that is never checked in. Tutorials, as you argued above, should tutor the preferred approach to be used in production code.

ok, then for consistency, should I update the sample to avoid `.ForEach` ?

**Comment by jrdouceur** [comment]
That would be my preference, yes.  Though it's not a super-strong pereference.

**Comment by jrdouceur** [comment]
I'll do the restructuring and push another commit.

**Review by rido-min — APPROVED** [review]

**Pull request merged**
