### PR TITLE
Keep elements in standard model immutable from parent-pointer updates

### PR DESCRIPTION
**Pull request by jrdouceur**

### CODE REVIEW

**Comment by rido-min** [comment]
do we have any issue to justify this change? should we add any test to validate?

**Comment by jrdouceur** [comment]
I believe this should fix the concurrency issue that Willow raised in email (but they have not yet created an issue for).  I don't have a repro of the issue, so I'm not completely sure this will address it, but there is definitely a bug here, so this change is at least an improvement in correctness.

However, the PR is failing the checks.  Specifically, the ci.yml action is failing on the docfx step.  I don't understand why this is failing.  The ADO PR pipeline also runs docfx, but it is passing.  And we just ran the apidocs.yml action successfully this morning, and it runs docfx.  So I'm quite confused.  I don't see anything special that the ci.yml is doing or not doing relative to apidocs.yml.

JD

________________________________

**Comment by jrdouceur** [comment]
:)

**Comment by jrdouceur** [comment]
Issue #86 is a different manifestation of the issue.  It occurs on Parse(), whereas the other form occurs on ParseAsync().

**Review by jaslawinMs — APPROVED** [review]

**Review by rido-min — APPROVED** [review]

**Pull request merged**
